//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupUtil.I18n.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BackupUtil.I18n.Resources.Strings_en", typeof(Strings_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string errorSourcePath {
            get {
                return ResourceManager.GetString("errorSourcePath", resourceCulture);
            }
        }
        
        internal static string errorTargetPath {
            get {
                return ResourceManager.GetString("errorTargetPath", resourceCulture);
            }
        }
        
        internal static string errorSameSourceTarget {
            get {
                return ResourceManager.GetString("errorSameSourceTarget", resourceCulture);
            }
        }
        
        internal static string errorSourceInTarget {
            get {
                return ResourceManager.GetString("errorSourceInTarget", resourceCulture);
            }
        }
        
        internal static string errorTargetPathEnd {
            get {
                return ResourceManager.GetString("errorTargetPathEnd", resourceCulture);
            }
        }
        
        internal static string errorSourceFileTargetDir {
            get {
                return ResourceManager.GetString("errorSourceFileTargetDir", resourceCulture);
            }
        }
        
        internal static string errorSourceDirTargetFile {
            get {
                return ResourceManager.GetString("errorSourceDirTargetFile", resourceCulture);
            }
        }
        
        internal static string errorSourceNotFound {
            get {
                return ResourceManager.GetString("errorSourceNotFound", resourceCulture);
            }
        }
        
        internal static string errorTargetInSource {
            get {
                return ResourceManager.GetString("errorTargetInSource", resourceCulture);
            }
        }
        
        internal static string errorFileFormatNotSupported {
            get {
                return ResourceManager.GetString("errorFileFormatNotSupported", resourceCulture);
            }
        }
        
        internal static string changeTypeModify {
            get {
                return ResourceManager.GetString("changeTypeModify", resourceCulture);
            }
        }
        
        internal static string changeTypeCreate {
            get {
                return ResourceManager.GetString("changeTypeCreate", resourceCulture);
            }
        }
        
        internal static string changeTypeDelete {
            get {
                return ResourceManager.GetString("changeTypeDelete", resourceCulture);
            }
        }
        
        internal static string changesToFiles {
            get {
                return ResourceManager.GetString("changesToFiles", resourceCulture);
            }
        }
        
        internal static string changesToDirectories {
            get {
                return ResourceManager.GetString("changesToDirectories", resourceCulture);
            }
        }
        
        internal static string IsOk {
            get {
                return ResourceManager.GetString("IsOk", resourceCulture);
            }
        }
        
        internal static string selectJobsToRun {
            get {
                return ResourceManager.GetString("selectJobsToRun", resourceCulture);
            }
        }
        
        internal static string errorInvalidJobFile {
            get {
                return ResourceManager.GetString("errorInvalidJobFile", resourceCulture);
            }
        }
        
        internal static string errorMaxJobs {
            get {
                return ResourceManager.GetString("errorMaxJobs", resourceCulture);
            }
        }
        
        internal static string selectJobsToRemove {
            get {
                return ResourceManager.GetString("selectJobsToRemove", resourceCulture);
            }
        }
        
        internal static string jobName {
            get {
                return ResourceManager.GetString("jobName", resourceCulture);
            }
        }
        
        internal static string jobTargetPath {
            get {
                return ResourceManager.GetString("jobTargetPath", resourceCulture);
            }
        }
        
        internal static string jobSourcePath {
            get {
                return ResourceManager.GetString("jobSourcePath", resourceCulture);
            }
        }
        
        internal static string jobDifferential {
            get {
                return ResourceManager.GetString("jobDifferential", resourceCulture);
            }
        }
        
        internal static string jobRecursive {
            get {
                return ResourceManager.GetString("jobRecursive", resourceCulture);
            }
        }
    }
}
