name: Build and test (linux-x64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: BackupUtil.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 9 SDK (preview)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore $Solution_Name

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Build solution
      run: dotnet publish $Solution_Name -r linux-x64 --configuration Release --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build and test (linux-x64)
        path: 'BackupUtil.Core/bin/Release/net9.0/linux-64/publish/'
