name: Build and test (win-x64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  Solution_Name: BackupUtil.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 9 SDK (preview)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Build solution
      run: dotnet publish $env:Solution_Name -r win-x64 --configuration Release --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WPF-Build
        path: 'BackupUtil.Core/bin/Release/net9.0-windows/win-x64/publish/'
