name: Build and test (win-x64)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'assets/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'assets/**'

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: BackupUtil.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 9 SDK (preview)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore $Solution_Name

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Build solution
      run: dotnet publish $Solution_Name -r win-x64 --configuration Release --no-restore

    - name: Upload BackupUtil.Core build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BackupUtil.Core Build (win-x64)
        path: 'BackupUtil.Core/bin/Release/net9.0/win-x64/publish'

    - name: Upload BackupUtil.Cli build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BackupUtil.Cli Build (win-x64)
        path: 'BackupUtil.Cli/bin/Release/net9.0/win-x64/publish'
